using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.LogEntries;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace GreyWardenPolicePurity
{
    internal sealed class GreyWardenAdoptionLogEntry : LogEntry, IChatNotification, IEncyclopediaLog
    {
        [SaveableField(1)]
        public readonly Hero AdoptedHero;

        [SaveableField(2)]
        private readonly string _originVillageName;

        public GreyWardenAdoptionLogEntry(Hero adoptedHero, string originVillageName)
        {
            AdoptedHero = adoptedHero;
            _originVillageName = originVillageName ?? string.Empty;
        }

        public bool IsVisibleNotification => true;

        public override CampaignTime KeepInHistoryTime =>
            CampaignTime.Years(Campaign.Current.Models.AgeModel.BecomeOldAge / 2f);

        public override ChatNotificationType NotificationType => PoliticalNotification(AdoptedHero?.Clan);

        internal static void AutoGeneratedStaticCollectObjectsGreyWardenAdoptionLogEntry(
            object o,
            List<object> collectedObjects)
        {
            ((GreyWardenAdoptionLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
        }

        protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
            base.AutoGeneratedInstanceCollectObjects(collectedObjects);
            collectedObjects.Add(AdoptedHero);
        }

        internal static object AutoGeneratedGetMemberValueAdoptedHero(object o)
        {
            return ((GreyWardenAdoptionLogEntry)o).AdoptedHero;
        }

        internal static object AutoGeneratedGetMemberValue_originVillageName(object o)
        {
            return ((GreyWardenAdoptionLogEntry)o)._originVillageName;
        }

        public TextObject GetNotificationText()
        {
            return BuildText(GwpText.Get("{=gwp_adoption_chat_notice}{HERO.LINK} was taken in by the Grey Wardens from {VILLAGE}."));
        }

        public bool IsVisibleInEncyclopediaPageOf(MBObjectBase obj)
        {
            MBObjectBase? entryTarget = obj;
            return entryTarget == AdoptedHero || entryTarget == AdoptedHero?.Clan;
        }

        public TextObject GetEncyclopediaText()
        {
            return BuildText(GwpText.Get("{=gwp_adoption_log_entry}{HERO.LINK} was taken in by the Grey Wardens from {VILLAGE} and brought back to the inner courtyard to be raised."));
        }

        public override string ToString()
        {
            return GetEncyclopediaText().ToString();
        }

        private TextObject BuildText(string template)
        {
            TextObject text = new TextObject(template);
            if (AdoptedHero?.CharacterObject != null)
            {
                StringHelpers.SetCharacterProperties("HERO", AdoptedHero.CharacterObject, text);
            }

            text.SetTextVariable("VILLAGE", string.IsNullOrWhiteSpace(_originVillageName) ? GwpText.Get("{=gwp_greywardenadoptionlogentry_003}Unknown Village") : _originVillageName);
            return text;
        }
    }
}
